"""Long-only historical replay using the exact live signal engine.

This module is research-only.  It never imports the broker adapter, never opens
a broker connection, and never submits an order.  Historical market data is fed
through LiveDirectionEngine so signal selection stays aligned with production.

Execution remains a proxy: entry and exit are assumed immediately filled at the
same adverse-one-tick limit prices generated by the live strategy.  Real queue
position, partial fills, entry timeout, cancel/replace and broker latency are
not simulated.
"""

from __future__ import annotations

import argparse
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta
import json
from pathlib import Path

from yuanta_live_runtime_v01.strategy import LiveDirectionEngine, ManagedPosition

from .direction_follow_backtest import (
    SPEC,
    SPEC_HASH,
    TAIPEI,
    _decision_times,
    _projected_net_pnl,
    load_session,
)


ANALYSIS_ID = "YUANTA_TOP30_LONG_ONLY_LIVE_PARITY_V0_1"
EXECUTION_MODEL = "IMMEDIATE_FULL_FILL_AT_LIVE_ADVERSE_ONE_TICK_PROXY"


@dataclass(frozen=True)
class LiveParityTrade:
    session_date: str
    stock_id: str
    stock_name: str
    side: str
    decision_time: str
    entry_time: str
    exit_time: str
    exit_reason: str
    score: float
    volume_delta: float
    large_trade_delta: float
    vwap_gap: float
    book_imbalance: float
    spread_bps: float
    entry_price: float
    exit_price: float
    quantity: int
    notional_used: float
    gross_pnl: float
    commission: int
    sell_tax: int
    net_pnl: float
    execution_model: str


def _parse_stamp(value: str) -> datetime:
    return datetime.fromisoformat(str(value).replace("Z", "+00:00")).astimezone(TAIPEI)


def _clock_on(session_date: str, value: str) -> datetime:
    base = datetime.strptime(session_date, "%Y%m%d").replace(tzinfo=TAIPEI)
    hour, minute = map(int, value.split(":"))
    return base.replace(hour=hour, minute=minute, second=0, microsecond=0)


def _validate_full_session_coverage(coverage: dict) -> None:
    statuses = list(coverage.get("source_statuses") or [])
    if not statuses or any(status != "COMPLETE" for status in statuses):
        raise RuntimeError(
            "LIVE-parity replay requires every source run to have status COMPLETE"
        )

    if int(coverage.get("callback_errors") or 0) != 0:
        raise RuntimeError(
            "LIVE-parity replay requires callback_errors=0"
        )

    session_date = str(coverage["session_date"])
    started = _parse_stamp(coverage["started_at_taipei"])
    ended = _parse_stamp(coverage["ended_at_taipei"])
    required_start = _clock_on(session_date, SPEC["entry_start"])
    required_end = _clock_on(session_date, SPEC["hard_exit_time"])

    if started > required_start:
        raise RuntimeError(
            f"LIVE-parity replay requires source coverage by {SPEC['entry_start']}"
        )

    if ended < required_end:
        raise RuntimeError(
            f"LIVE-parity replay requires source coverage through {SPEC['hard_exit_time']}"
        )


def _record_tick(engine: LiveDirectionEngine, symbol: str, row: dict) -> None:
    engine.record_tick(
        symbol,
        at=row["time"],
        price=row["price"],
        volume=row["volume"],
        bid=row["bid"],
        ask=row["ask"],
        flag=row["flag"],
        serial=row["serial"],
    )


def _record_book(engine: LiveDirectionEngine, symbol: str, row: dict) -> None:
    # load_session() already converts a five-level book into total bid/ask
    # volume plus best bid/ask. Feeding those same aggregates to the live engine
    # reproduces the state consumed by LiveDirectionEngine._signal_for().
    engine.record_book_combined(
        symbol,
        at=row["time"],
        buy_prices=[row["best_bid"]],
        buy_volumes=[row["buy_volume"]],
        sell_prices=[row["best_ask"]],
        sell_volumes=[row["sell_volume"]],
    )


def _feed_until(
    engine: LiveDirectionEngine,
    stocks: dict[str, dict],
    tick_indexes: dict[str, int],
    book_indexes: dict[str, int],
    cutoff: datetime,
) -> None:
    for symbol, data in stocks.items():
        tick_index = tick_indexes[symbol]
        ticks = data["ticks"]
        while tick_index < len(ticks) and ticks[tick_index]["time"] <= cutoff:
            _record_tick(engine, symbol, ticks[tick_index])
            tick_index += 1
        tick_indexes[symbol] = tick_index

        book_index = book_indexes[symbol]
        books = data["books"]
        while book_index < len(books) and books[book_index]["time"] <= cutoff:
            _record_book(engine, symbol, books[book_index])
            book_index += 1
        book_indexes[symbol] = book_index


def replay_session(
    stocks: dict[str, dict],
    coverage: dict,
    capital: int = 190000,
    *,
    exit_quote_staleness_seconds: float = 3.0,
) -> tuple[LiveParityTrade | None, dict]:
    _validate_full_session_coverage(coverage)

    session_date = str(coverage["session_date"])
    metadata = {
        symbol: str(data.get("meta", {}).get("stock_name", symbol))
        for symbol, data in stocks.items()
    }

    engine = LiveDirectionEngine(metadata, capital_twd=capital)
    tick_indexes = {symbol: 0 for symbol in stocks}
    book_indexes = {symbol: 0 for symbol in stocks}

    diagnostics = {
        "session_date": session_date,
        "long_only": True,
        "source_statuses": list(coverage.get("source_statuses") or []),
        "callback_errors": int(coverage.get("callback_errors") or 0),
        "selected_trade": False,
        "execution_model": EXECUTION_MODEL,
    }

    candidate = None

    for decision in _decision_times(
        session_date,
        SPEC["entry_start"],
        SPEC["last_entry_time"],
    ):
        _feed_until(
            engine,
            stocks,
            tick_indexes,
            book_indexes,
            decision,
        )

        candidate = engine.choose_entry(decision, allow_short=False)
        if candidate is not None:
            break

    if candidate is None:
        diagnostics["reason"] = "NO_LONG_ENTRY"
        return None, diagnostics

    diagnostics["selected_trade"] = True
    diagnostics["stock_id"] = candidate.stock_id
    diagnostics["decision_time"] = candidate.decision_time.isoformat()

    position = ManagedPosition(
        stock_id=candidate.stock_id,
        stock_name=candidate.stock_name,
        side="LONG",
        quantity=candidate.quantity,
        entry_price=candidate.entry_price,
        entry_order_id="BACKTEST_PROXY",
        entry_time=candidate.decision_time,
    )

    data = stocks[candidate.stock_id]
    tick_index = tick_indexes[candidate.stock_id]
    book_index = book_indexes[candidate.stock_id]

    events: list[tuple[datetime, int, str, dict | None]] = []

    for row in data["ticks"][tick_index:]:
        events.append((row["time"], 0, "tick", row))

    for row in data["books"][book_index:]:
        events.append((row["time"], 1, "book", row))

    end_time = _parse_stamp(coverage["ended_at_taipei"])
    interval = timedelta(seconds=int(SPEC["decision_interval_seconds"]))
    next_decision = candidate.decision_time + interval

    while next_decision <= end_time:
        events.append((next_decision, 2, "decision", None))
        next_decision += interval

    events.sort(key=lambda item: (item[0], item[1]))

    for at, _priority, kind, row in events:
        reversal = False

        if kind == "tick":
            assert row is not None
            _record_tick(engine, candidate.stock_id, row)
        elif kind == "book":
            assert row is not None
            _record_book(engine, candidate.stock_id, row)
        else:
            reversal = engine.opposite_signal(position, at)
            engine.last_decision = at

        exit_decision = engine.evaluate_exit(
            position,
            at,
            reversal=reversal,
            max_quote_age_seconds=exit_quote_staleness_seconds,
        )

        if exit_decision is None:
            continue

        gross, commission, sell_tax, net_pnl = _projected_net_pnl(
            "LONG",
            candidate.entry_price,
            exit_decision.price,
            candidate.quantity,
        )

        trade = LiveParityTrade(
            session_date=session_date,
            stock_id=candidate.stock_id,
            stock_name=candidate.stock_name,
            side="LONG",
            decision_time=candidate.decision_time.isoformat(),
            entry_time=candidate.decision_time.isoformat(),
            exit_time=at.isoformat(),
            exit_reason=exit_decision.reason,
            score=candidate.score,
            volume_delta=candidate.volume_delta,
            large_trade_delta=candidate.large_trade_delta,
            vwap_gap=candidate.vwap_gap,
            book_imbalance=candidate.book_imbalance,
            spread_bps=candidate.spread_bps,
            entry_price=candidate.entry_price,
            exit_price=exit_decision.price,
            quantity=candidate.quantity,
            notional_used=candidate.entry_price * candidate.quantity,
            gross_pnl=gross,
            commission=commission,
            sell_tax=sell_tax,
            net_pnl=net_pnl,
            execution_model=EXECUTION_MODEL,
        )
        return trade, diagnostics

    diagnostics["reason"] = "EXIT_NOT_SCORABLE_FROM_AVAILABLE_QUOTES"
    return None, diagnostics


def build_report(
    session_runs: dict[str, list[Path]],
    capital: int = 190000,
) -> dict:
    coverages = []
    diagnostics = []
    trades = []

    for _, run_dirs in sorted(session_runs.items()):
        stocks, coverage = load_session(run_dirs)
        coverages.append(coverage)

        trade, session_diagnostics = replay_session(
            stocks,
            coverage,
            capital,
        )
        diagnostics.append(session_diagnostics)

        if trade is not None:
            trades.append(trade)

    net = round(sum(trade.net_pnl for trade in trades), 2)

    return {
        "analysis_id": ANALYSIS_ID,
        "strategy_spec": SPEC,
        "strategy_spec_hash": SPEC_HASH,
        "capital_twd": capital,
        "long_only": True,
        "maximum_trades_per_session": int(SPEC["maximum_trades_per_session"]),
        "execution_model": EXECUTION_MODEL,
        "execution_limitations": [
            "proxy assumes immediate full fill at the live strategy limit price",
            "does not model queue position or broker latency",
            "does not model partial entry fills or the live entry timeout",
            "does not model cancel/replace or exit rescue retries",
        ],
        "coverage": coverages,
        "diagnostics": diagnostics,
        "trades": [asdict(trade) for trade in trades],
        "session_count": len(coverages),
        "trade_count": len(trades),
        "winning_trades": sum(trade.net_pnl > 0 for trade in trades),
        "net_pnl_twd": net,
        "return_on_capital": round(net / capital, 8),
        "actual_orders": 0,
        "actual_fills": 0,
        "broker_order_calls": 0,
        "interpretation": (
            "HISTORICAL_LIVE_SIGNAL_PARITY_WITH_EXECUTION_PROXY_NOT_ACTUAL_FILL_PERFORMANCE"
        ),
    }


def _session_arg(value: str) -> tuple[str, list[Path]]:
    try:
        date, paths = value.split("=", 1)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            "use YYYYMMDD=RUN_DIR[,RUN_DIR]"
        ) from exc
    return date, [Path(path) for path in paths.split(",")]


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Long-only historical replay through the production live signal engine"
    )
    parser.add_argument(
        "--session",
        action="append",
        required=True,
        type=_session_arg,
    )
    parser.add_argument("--capital", type=int, default=190000)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()

    report = build_report(dict(args.session), args.capital)
    rendered = json.dumps(report, ensure_ascii=False, indent=2) + "\n"

    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with args.output.open("x", encoding="utf-8") as handle:
            handle.write(rendered)
    else:
        print(rendered, end="")


if __name__ == "__main__":
    main()
